title: The Haynes Institute
description: A simple archive and study house for Theology, American history, and classical education.
url: "https://haynesinstitute.org"
baseurl: ""

markdown: kramdown
permalink: pretty

collections:
  resources:
    output: true
    permalink: /resources/:name/
  guides:
    output: true
    permalink: /guides/:name/
  heritage:
    output: true
    permalink: /heritage-american/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: resources
    values:
      layout: resource
  - scope:
      path: ""
      type: guides
    values:
      layout: page
  - scope:
      path: ""
      type: heritage
    values:
      layout: page

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - market_research_for_haynes.md
